### ISSUE TITLE
Extending $platform throws TypeError

### ISSUE THREAD

**Issue by kroitor** [xpl/useless#2]
I'm extending $platform like this:
```javascript
$platform.isBigEndian = (() => 
        (new DataView (new Int16Array ([256]).buffer).getUint16 (0) === 256)) ()
```
It did work fine, but stopped working after commit [36c0f63](https://github.com/xpl/useless/commit/36c0f6369bc1226a1a8eb9e253c91240534c9873)

**Comment by kroitor** [comment]
This is the exception thrown:
```
Uncaught TypeError: Can't add property isBigEndian, object is not extensible(anonymous function) ```

**Comment by xpl** [comment]
It was caused by `Object.freeze` on the `$platform` object. Removed that.
