### ISSUE TITLE
Base64.js ( useless/base/3rd/Base64.js ) is outdated

### ISSUE THREAD

**Issue by kroitor** [xpl/useless#5]
What's the point of having a 3rd party implementation of Base64 encoding anyways? Afaik, [Base64.js](https://github.com/xpl/useless/blob/master/base/3rd/Base64.js) should be deprecated from now on in favor of btoa / atob JS atoms (web interface) or Buffer objects (Node.js). Is there a performance implication? I would say no, that 3rd-party code is naive (bitwise shifting is not accelerated in JS environment). So, why keeping it?

```javascript
// within a web browser

$mixin (String, {
    $property: {
        btoa: function () { return btoa (this) },
        atob: function () { return atob (this) },
    }
}

// with Node.js

console.log (new Buffer ('Hello World!').toString ('base64'))
console.log (new Buffer (b64Encoded, 'base64').toString ())
```

**Comment by xpl** [comment]
Removed as obsolete.
